### ISSUE TITLE
改回透過自有主機排程更新資料

### ISSUE THREAD

**Issue by kiang** [kiang/cit_water#6]
觀察了一下，現在透過 github actions 更新資料的頻率不太穩定，排程 10 分鐘進行一次，但實際上大概 30-60 分鐘才會被執行一次，所以改回透過自己的主機進行了

FYI @typebrook

**Comment by typebrook** [comment]
@kiang 

的確，Github 的Runner應該每小時執行一次就是極限了。這類更新頻繁的資料還是用自己的機器跑比較好
